import testBigInteger from './biginteger.js';
import testCipher from './cipher/index.js';
import testHash from './hash/index.js';
import testCrypto from './crypto.js';
import testElliptic from './ecdsa_eddsa.js';
import testBrainpoolRFC7027 from './brainpool_rfc7027.js';
import testECDH from './ecdh.js';
import testPKCS5 from './pkcs5.js';
import testAESKW from './aes_kw.js';
import testHKDF from './hkdf.js';
import testGCM from './gcm.js';
import testEAX from './eax.js';
import testOCB from './ocb.js';
import testRSA from './rsa.js';
import testValidate from './validate.js';

export default () => describe('Crypto', function () {
  testBigInteger();
  testCipher();
  testHash();
  testCrypto();
  testElliptic();
  testBrainpoolRFC7027();
  testECDH();
  testPKCS5();
  testAESKW();
  testHKDF();
  testGCM();
  testEAX();
  testOCB();
  testRSA();
  testValidate();
});
