name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: JSDoc

    runs-on: ubuntu-latest
    permissions: {}

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version-file: package.json
        package-manager-cache: false # enabled by default with `devEngine.packageManager`
    - run: npm install -g "npm@$(node -p 'require("./package.json").devEngines.packageManager.version')"
    - run: npm ci --ignore-scripts
    - run: npm run docs
